name: generic_network
channels:
  - conda-forge
  - defaults
dependencies:
  - graph-tool=2.37
  - ipykernel=5.3.4
  - matplotlib=3.3
  - numpy=1.20.1
  - pandas=1.2.2
  - python=3.9
  - python-igraph=0.8.3
  - seaborn=0.11.1
