name: generic_expression

channels:
- conda-forge
- r
- bioconda
dependencies:
- r::r=3.6.0
- r::r-devtools
- r::r-stringi
- bioconda::bioconductor-limma
- bioconda::bioconductor-deseq2
- bioconda::bioconductor-recount
- bioconda::bioconductor-fgsea
- bioconda::bioconductor-gsva
- bioconda::bioconductor-DEFormats
- bioconda::bioconductor-clusterprofiler
- conda-forge::python=3.7
- conda-forge::scikit-learn
- conda-forge::numpy=1.19.5
- conda-forge::pandas=0.23.4
- conda-forge::seaborn=0.10
- conda-forge::umap-learn
- conda-forge::scipy=1.3.0
- conda-forge::plotnine=0.5.1
- conda-forge::jupyter
- conda-forge::ipykernel=5.1.1
- conda-forge::nb_conda_kernels
- conda-forge::gxx_linux-64
- conda-forge::rpy2=2.9.4
- conda-forge::libiconv=1.15
- conda-forge::r-biocmanager
- conda-forge::r-gsa

- pip=19.2.1
- pip:
  - matplotlib==3.0.0
  - ponyo==0.2
  - matplotlib-venn
  - svgutils==0.3.1
  - black==20.8b1
  - flake8==3.8.4
  - pre_commit==2.9.3
  - jupytext==1.9.1
